version: '3.8'

services:
  # Backend Service
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - db-mongo
      - datamatrix-service
    networks:
      - server-network
    env_file:
      - .env.production
    environment:
      - THIRD_PARTY_DETECTOR_URL=http://datamatrix-service:5001
      - NODE_ENV=production

  # DataMatrix Detection Service
  datamatrix-service:
    build:
      context: /root/matrix-detection
      dockerfile: Dockerfile
    container_name: datamatrix-service
    ports:
      - "5001:5001"
    volumes:
      - /root/matrix-detection/uploads:/app/uploads
      - /root/matrix-detection/outputs:/app/outputs
    restart: unless-stopped
    networks:
      - server-network
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MongoDB Service
  db-mongo:
    container_name: db-mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - server-network

volumes:
  mongo-data:

networks:
  server-network:
    driver: bridge