version: '3.8'

services:
  # Backend Service
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - db-mongo
    networks:
      - server-network

  # MongoDB Service
  db-mongo:
    container_name: db-mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - server-network

volumes:
  mongo-data:

networks:
  server-network:
    driver: bridge